import mongoose from "mongoose";
import { DB_NAME } from "../../constants.js";
import Property from "../models/Property.js";
import User from "../models/User.js";
import dotenv from "dotenv";

dotenv.config({ path: "./.env" });

console.log("Starting seed script...");
console.log("MongoDB URI set:", !!process.env.MONGODB_URI);

const properties = [
  {
    title: "Modern Downtown Apartment with Skyline View",
    description: "Stunning modern apartment in the heart of downtown with floor-to-ceiling windows offering breathtaking skyline views. Features an open-concept kitchen with quartz countertops, hardwood floors throughout, and a private balcony.",
    price: 450000,
    bedrooms: 2,
    bathrooms: 2,
    area: 1200,
    propertyType: "apartment",
    status: "available",
    address: { street: "123 Main St", city: "New York", state: "NY", zipcode: "10001", country: "USA" },
    location: { type: "Point", coordinates: [-74.006, 40.7128] },
    amenities: ["Doorman", "Gym", "Pool", "Parking", "Laundry"],
    isFeatured: true,
    meta: { furnished: true, yearBuilt: 2020 }
  },
  {
    title: "Spacious Family Home with Backyard",
    description: "Beautiful 4-bedroom home in a quiet suburban neighborhood. Large backyard with mature trees, updated kitchen with stainless steel appliances, finished basement, and attached two-car garage.",
    price: 675000,
    bedrooms: 4,
    bathrooms: 3,
    area: 2800,
    propertyType: "house",
    status: "available",
    address: { street: "456 Oak Ave", city: "Austin", state: "TX", zipcode: "73301", country: "USA" },
    location: { type: "Point", coordinates: [-97.7431, 30.2672] },
    amenities: ["Garage", "Backyard", "Fireplace", "Central AC", "Hardwood Floors"],
    isFeatured: true,
    meta: { furnished: false, yearBuilt: 2015 }
  },
  {
    title: "Luxury Beachfront Villa",
    description: "Exquisite beachfront villa with panoramic ocean views. Private pool, outdoor entertaining area, gourmet chef's kitchen, and floor-to-ceiling windows. Master suite features a spa-like bathroom and private terrace.",
    price: 2500000,
    bedrooms: 5,
    bathrooms: 5,
    area: 4500,
    propertyType: "villa",
    status: "available",
    address: { street: "789 Ocean Dr", city: "Miami", state: "FL", zipcode: "33101", country: "USA" },
    location: { type: "Point", coordinates: [-80.1918, 25.7617] },
    amenities: ["Pool", "Ocean View", "Outdoor Kitchen", "Smart Home", "Security System"],
    isFeatured: true,
    meta: { furnished: true, yearBuilt: 2022 }
  },
  {
    title: "Cozy Condo in Historic District",
    description: "Charming condo located in the historic district. Original exposed brick walls, high ceilings, updated bathroom, and a modern kitchen. Walking distance to restaurants, shops, and public transit.",
    price: 310000,
    bedrooms: 1,
    bathrooms: 1,
    area: 750,
    propertyType: "condo",
    status: "available",
    address: { street: "321 Elm St", city: "Boston", state: "MA", zipcode: "02101", country: "USA" },
    location: { type: "Point", coordinates: [-71.0589, 42.3601] },
    amenities: ["Bike Storage", "Rooftop Access", "Laundry", "Storage Unit"],
    isFeatured: false,
    meta: { furnished: false, yearBuilt: 1920 }
  },
  {
    title: "Commercial Space in Financial District",
    description: "Prime commercial real estate in the financial district. Open floor plan ideal for offices or retail. High foot traffic area with excellent visibility. Recently renovated with modern finishes.",
    price: 1200000,
    bedrooms: 0,
    bathrooms: 2,
    area: 3200,
    propertyType: "commercial",
    status: "available",
    address: { street: "555 Market St", city: "San Francisco", state: "CA", zipcode: "94105", country: "USA" },
    location: { type: "Point", coordinates: [-122.3997, 37.793] },
    amenities: ["Elevator", "Security", "Loading Dock", "Conference Room"],
    isFeatured: false,
    meta: { furnished: false, yearBuilt: 2005 }
  },
  {
    title: "Vacant Land with Mountain Views",
    description: "Beautiful 5-acre lot with stunning mountain views. Perfect for building your dream home. Utilities available at the street. Zoned for residential use. Close to hiking trails and national forest.",
    price: 175000,
    bedrooms: 0,
    bathrooms: 0,
    area: 217800,
    propertyType: "land",
    status: "available",
    address: { street: "100 Mountain Rd", city: "Denver", state: "CO", zipcode: "80201", country: "USA" },
    location: { type: "Point", coordinates: [-104.9903, 39.7392] },
    amenities: ["Utilities Available"],
    isFeatured: false,
    meta: { yearBuilt: null }
  },
  {
    title: "Chic Urban Loft in Arts District",
    description: "Industrial-chic loft in the vibrant arts district. Soaring 14-foot ceilings, polished concrete floors, exposed ductwork, and a chef's kitchen with waterfall island. Steps from galleries and trendy restaurants.",
    price: 525000,
    bedrooms: 2,
    bathrooms: 2,
    area: 1400,
    propertyType: "apartment",
    status: "available",
    address: { street: "888 Arts Blvd", city: "Los Angeles", state: "CA", zipcode: "90013", country: "USA" },
    location: { type: "Point", coordinates: [-118.2437, 34.0522] },
    amenities: ["Gym", "Rooftop Deck", "Parking", "Pet Friendly"],
    isFeatured: true,
    meta: { furnished: true, yearBuilt: 2018 }
  },
  {
    title: "Charming Craftsman Bungalow",
    description: "Well-maintained craftsman bungalow with original woodwork, built-in bookshelves, and a cozy fireplace. Updated kitchen and bathrooms. Large front porch and fenced backyard with garden beds.",
    price: 485000,
    bedrooms: 3,
    bathrooms: 2,
    area: 1800,
    propertyType: "house",
    status: "pending",
    address: { street: "742 Maple Dr", city: "Portland", state: "OR", zipcode: "97201", country: "USA" },
    location: { type: "Point", coordinates: [-122.6765, 45.5231] },
    amenities: ["Fireplace", "Garden", "Front Porch", "Detached Garage"],
    isFeatured: false,
    meta: { furnished: false, yearBuilt: 1925 }
  },
  {
    title: "Penthouse Suite with Rooftop Terrace",
    description: "Exclusive penthouse with a private rooftop terrace featuring a hot tub, outdoor kitchen, and panoramic city views. Interior features include a wine cellar, home theater, and designer finishes throughout.",
    price: 3200000,
    bedrooms: 3,
    bathrooms: 3,
    area: 3500,
    propertyType: "condo",
    status: "available",
    address: { street: "1 Luxury Tower Dr", city: "Chicago", state: "IL", zipcode: "60601", country: "USA" },
    location: { type: "Point", coordinates: [-87.6298, 41.8781] },
    amenities: ["Concierge", "Valet Parking", "Spa", "Wine Cellar", "Home Theater", "Rooftop Terrace"],
    isFeatured: true,
    meta: { furnished: true, yearBuilt: 2021 }
  },
  {
    title: "Townhouse in Gated Community",
    description: "Modern townhouse in a secure gated community. Three levels with a rooftop deck. Gourmet kitchen, spacious master suite with walk-in closet, and a two-car garage. Community pool and clubhouse access.",
    price: 580000,
    bedrooms: 3,
    bathrooms: 3,
    area: 2100,
    propertyType: "townhouse",
    status: "available",
    address: { street: "256 Safe Harbor Ln", city: "Seattle", state: "WA", zipcode: "98101", country: "USA" },
    location: { type: "Point", coordinates: [-122.3321, 47.6062] },
    amenities: ["Gated", "Pool", "Clubhouse", "Garage", "Rooftop Deck"],
    isFeatured: false,
    meta: { furnished: false, yearBuilt: 2019 }
  },
  {
    title: "Studio Apartment Near University",
    description: "Compact and efficient studio apartment perfect for students or young professionals. Located near the university campus. Includes all utilities, high-speed internet, and access to communal laundry facilities.",
    price: 180000,
    bedrooms: 0,
    bathrooms: 1,
    area: 450,
    propertyType: "apartment",
    status: "rented",
    address: { street: "420 College Ave", city: "Ann Arbor", state: "MI", zipcode: "48103", country: "USA" },
    location: { type: "Point", coordinates: [-83.743, 42.2808] },
    amenities: ["Utilities Included", "Internet", "Laundry", "Furnished"],
    isFeatured: false,
    meta: { furnished: true, yearBuilt: 2010 }
  },
  {
    title: "Equestrian Estate with Barn",
    description: "Magnificent estate on 20 acres with a 6-stall barn, riding arena, and paddocks. The main house features 6 bedrooms, a gourmet kitchen, wine room, and a resort-style pool. Guest house included.",
    price: 4500000,
    bedrooms: 6,
    bathrooms: 6,
    area: 6500,
    propertyType: "house",
    status: "available",
    address: { street: "1000 Equestrian Way", city: "Nashville", state: "TN", zipcode: "37201", country: "USA" },
    location: { type: "Point", coordinates: [-86.7816, 36.1627] },
    amenities: ["Barn", "Pool", "Guest House", "Wine Room", "Gated Entry"],
    isFeatured: true,
    meta: { furnished: true, yearBuilt: 2008 }
  },
  {
    title: "Lakefront Cabin Retreat",
    description: "Secluded lakefront cabin surrounded by pine forests. Perfect getaway with a stone fireplace, wraparound deck, dock, and canoe. Open-plan living area with cathedral ceilings and rustic finishes.",
    price: 395000,
    bedrooms: 3,
    bathrooms: 2,
    area: 1600,
    propertyType: "house",
    status: "available",
    address: { street: "57 Lakeview Dr", city: "Lake Tahoe", state: "CA", zipcode: "96145", country: "USA" },
    location: { type: "Point", coordinates: [-120.0324, 39.0968] },
    amenities: ["Lake Access", "Dock", "Fireplace", "Deck", "Canoe"],
    isFeatured: false,
    meta: { furnished: true, yearBuilt: 1995 }
  },
  {
    title: "Modern Apartment with Smart Home Features",
    description: "State-of-the-art smart apartment with automated lighting, climate control, and security system. Open layout with Italian marble floors, Miele appliances, and a spa-like bathroom with rainfall shower.",
    price: 620000,
    bedrooms: 2,
    bathrooms: 2,
    area: 1100,
    propertyType: "apartment",
    status: "available",
    address: { street: "900 Tech Park Dr", city: "San Jose", state: "CA", zipcode: "95101", country: "USA" },
    location: { type: "Point", coordinates: [-121.8863, 37.3382] },
    amenities: ["Smart Home", "Gym", "Concierge", "EV Charging", "Package Room"],
    isFeatured: false,
    meta: { furnished: true, yearBuilt: 2023 }
  },
  {
    title: "Fixer-Upper with Potential",
    description: "Great opportunity for investors or handy homeowners. Solid structure needing cosmetic updates. Desirable neighborhood with good schools. Large lot with room for expansion. Priced below market value.",
    price: 250000,
    bedrooms: 3,
    bathrooms: 1,
    area: 1400,
    propertyType: "house",
    status: "available",
    address: { street: "1500 Fixer Ln", city: "Detroit", state: "MI", zipcode: "48201", country: "USA" },
    location: { type: "Point", coordinates: [-83.0458, 42.3314] },
    amenities: ["Large Lot", "Good Schools Nearby"],
    isFeatured: false,
    meta: { furnished: false, yearBuilt: 1950 }
  },
  {
    title: "Oceanview Apartment in Waikiki",
    description: "Beautiful apartment with direct ocean views in the heart of Waikiki. Recently renovated with tropical-inspired design. Lanai overlooking the beach. Resort amenities include pool, tennis courts, and restaurant.",
    price: 850000,
    bedrooms: 2,
    bathrooms: 2,
    area: 950,
    propertyType: "apartment",
    status: "available",
    address: { street: "222 Beach Walk", city: "Honolulu", state: "HI", zipcode: "96815", country: "USA" },
    location: { type: "Point", coordinates: [-157.8583, 21.3069] },
    amenities: ["Pool", "Tennis", "Ocean View", "Resort Access", "Parking"],
    isFeatured: true,
    meta: { furnished: true, yearBuilt: 2016 }
  },
  {
    title: "Suburban Split-Level Home",
    description: "Classic split-level home in a family-friendly neighborhood. Formal living and dining rooms, updated kitchen, family room with fireplace, and a large backyard with deck. Top-rated school district.",
    price: 420000,
    bedrooms: 4,
    bathrooms: 2,
    area: 2200,
    propertyType: "house",
    status: "available",
    address: { street: "78 Suburbia Ct", city: "Raleigh", state: "NC", zipcode: "27601", country: "USA" },
    location: { type: "Point", coordinates: [-78.6382, 35.7796] },
    amenities: ["Deck", "Fireplace", "Garage", "Central AC", "School District"],
    isFeatured: false,
    meta: { furnished: false, yearBuilt: 1985 }
  },
  {
    title: "Industrial Warehouse Conversion",
    description: "Unique live-work warehouse conversion with massive open spaces. 20-foot ceilings, oversized windows, and a mezzanine level. Ideal for artists or creatives seeking an unconventional living space.",
    price: 650000,
    bedrooms: 2,
    bathrooms: 2,
    area: 3000,
    propertyType: "commercial",
    status: "available",
    address: { street: "44 Industrial Blvd", city: "Brooklyn", state: "NY", zipcode: "11201", country: "USA" },
    location: { type: "Point", coordinates: [-73.9442, 40.6782] },
    amenities: ["High Ceilings", "Loading Dock", "Natural Light", "Open Floor Plan"],
    isFeatured: false,
    meta: { furnished: false, yearBuilt: 1920 }
  },
  {
    title: "Golf Course Villa",
    description: "Elegant villa overlooking the 7th fairway of a championship golf course. Open floor plan with golf views from every room. Community amenities include golf club membership, pool, and fitness center.",
    price: 780000,
    bedrooms: 3,
    bathrooms: 3,
    area: 2400,
    propertyType: "villa",
    status: "available",
    address: { street: "12 Fairway Dr", city: "Scottsdale", state: "AZ", zipcode: "85250", country: "USA" },
    location: { type: "Point", coordinates: [-111.926, 33.5092] },
    amenities: ["Golf View", "Pool", "Fitness Center", "Club Membership", "Covered Patio"],
    isFeatured: false,
    meta: { furnished: false, yearBuilt: 2017 }
  },
  {
    title: "Affordable Starter Home",
    description: "Perfect first home with 3 bedrooms and a fenced yard. Updated windows, new HVAC system, and fresh paint throughout. Quiet cul-de-sac location with easy highway access. Move-in ready.",
    price: 295000,
    bedrooms: 3,
    bathrooms: 1,
    area: 1100,
    propertyType: "house",
    status: "available",
    address: { street: "300 Starter Ln", city: "Phoenix", state: "AZ", zipcode: "85001", country: "USA" },
    location: { type: "Point", coordinates: [-112.074, 33.4484] },
    amenities: ["Fenced Yard", "New HVAC", "Cul-de-Sac", "Hardwood Floors"],
    isFeatured: false,
    meta: { furnished: false, yearBuilt: 1970 }
  },
  {
    title: "Mid-Century Modern Masterpiece",
    description: "Iconic mid-century modern home designed by a notable architect. Walls of glass, post-and-beam construction, flagstone floors, and a courtyard with reflecting pool. Original period fixtures throughout.",
    price: 1250000,
    bedrooms: 4,
    bathrooms: 3,
    area: 3200,
    propertyType: "house",
    status: "sold",
    address: { street: "55 Architecture Way", city: "Palm Springs", state: "CA", zipcode: "92262", country: "USA" },
    location: { type: "Point", coordinates: [-116.5453, 33.8303] },
    amenities: ["Pool", "Courtyard", "Mountain View", "Original Fixtures"],
    isFeatured: false,
    meta: { furnished: false, yearBuilt: 1962 }
  },
  {
    title: "High-Rise Corner Unit",
    description: "Bright corner unit on the 35th floor with dual-aspect views. Floor-to-ceiling windows, open kitchen with island, and a built-in workspace. Building amenities include 24/7 concierge and rooftop lounge.",
    price: 750000,
    bedrooms: 2,
    bathrooms: 2,
    area: 1300,
    propertyType: "condo",
    status: "available",
    address: { street: "500 Sky Tower Blvd", city: "Atlanta", state: "GA", zipcode: "30301", country: "USA" },
    location: { type: "Point", coordinates: [-84.388, 33.749] },
    amenities: ["Concierge", "Rooftop Lounge", "Gym", "Valet", "Business Center"],
    isFeatured: false,
    meta: { furnished: false, yearBuilt: 2020 }
  },
  {
    title: "Garden Apartment with Private Yard",
    description: "Ground-floor garden apartment with a private fenced yard and patio. Updated eat-in kitchen, generous closet space, and in-unit washer/dryer. Quiet building in a tree-lined neighborhood.",
    price: 340000,
    bedrooms: 2,
    bathrooms: 1,
    area: 850,
    propertyType: "apartment",
    status: "available",
    address: { street: "88 Garden Path", city: "Philadelphia", state: "PA", zipcode: "19101", country: "USA" },
    location: { type: "Point", coordinates: [-75.1652, 39.9526] },
    amenities: ["Private Yard", "In-Unit Laundry", "Patio", "Storage"],
    isFeatured: false,
    meta: { furnished: false, yearBuilt: 2000 }
  },
  {
    title: "Ski Chalet with Slope Access",
    description: "Beautiful ski chalet with direct slope access. Stone fireplace, hot tub on the deck, ski storage, and a mudroom with boot warmers. Open-plan living with pine ceilings and mountain views.",
    price: 950000,
    bedrooms: 4,
    bathrooms: 3,
    area: 2800,
    propertyType: "house",
    status: "available",
    address: { street: "7 Ski Run Rd", city: "Aspen", state: "CO", zipcode: "81611", country: "USA" },
    location: { type: "Point", coordinates: [-106.8175, 39.1911] },
    amenities: ["Ski Access", "Hot Tub", "Fireplace", "Deck", "Ski Storage"],
    isFeatured: true,
    meta: { furnished: true, yearBuilt: 2012 }
  },
  {
    title: "Urban Townhouse with Garage",
    description: "Modern townhouse in a trendy neighborhood. Rooftop terrace with city skyline views, chef's kitchen, hardwood floors throughout, and a attached two-car garage. Walking score of 95.",
    price: 725000,
    bedrooms: 3,
    bathrooms: 3,
    area: 2000,
    propertyType: "townhouse",
    status: "available",
    address: { street: "250 Urban Wy", city: "Washington", state: "DC", zipcode: "20001", country: "USA" },
    location: { type: "Point", coordinates: [-77.0369, 38.9072] },
    amenities: ["Rooftop Terrace", "Garage", "Hardwood Floors", "Smart Thermostat"],
    isFeatured: false,
    meta: { furnished: false, yearBuilt: 2018 }
  },
  {
    title: "Retirement Community Villa",
    description: "Low-maintenance villa in a 55+ active adult community. Single-level living with open floor plan, upgraded kitchen, and a screened lanai. Community features golf, tennis, clubhouse, and social activities.",
    price: 380000,
    bedrooms: 2,
    bathrooms: 2,
    area: 1500,
    propertyType: "villa",
    status: "available",
    address: { street: "60 Golden Years Blvd", city: "Sarasota", state: "FL", zipcode: "34230", country: "USA" },
    location: { type: "Point", coordinates: [-82.5306, 27.3364] },
    amenities: ["Clubhouse", "Golf", "Tennis", "Pool", "Social Activities"],
    isFeatured: false,
    meta: { furnished: false, yearBuilt: 2015 }
  },
  {
    title: "Historic Brownstone in Park Slope",
    description: "Magnificent brownstone with original details including crown moldings, wainscoting, and a grand staircase. Updated systems and kitchen. Garden level with private outdoor space. Prime Park Slope location.",
    price: 3800000,
    bedrooms: 5,
    bathrooms: 4,
    area: 4000,
    propertyType: "townhouse",
    status: "available",
    address: { street: "123 Historic Ave", city: "Brooklyn", state: "NY", zipcode: "11215", country: "USA" },
    location: { type: "Point", coordinates: [-73.9818, 40.6602] },
    amenities: ["Garden", "Original Details", "Fireplace", "Cellar", "Deeded Parking"],
    isFeatured: true,
    meta: { furnished: false, yearBuilt: 1901 }
  },
  {
    title: "College Town Investment Property",
    description: "Well-maintained duplex near the university campus. Each unit has 2 bedrooms and 1 bathroom. Currently fully leased with strong rental history. Excellent cap rate and long-term appreciation potential.",
    price: 520000,
    bedrooms: 4,
    bathrooms: 2,
    area: 2400,
    propertyType: "house",
    status: "rented",
    address: { street: "400 University Ave", city: "Madison", state: "WI", zipcode: "53701", country: "USA" },
    location: { type: "Point", coordinates: [-89.4012, 43.0731] },
    amenities: ["Multi-Unit", "Laundry", "Off-Street Parking", "Near Campus"],
    isFeatured: false,
    meta: { furnished: false, yearBuilt: 1990 }
  },
  {
    title: "Desert Modern Home",
    description: "Stunning desert modern home with a courtyard entry, rammed earth walls, and solar panels. Open-concept interior flows to a patio with a negative-edge pool. Sustainable design meets luxury living.",
    price: 1450000,
    bedrooms: 4,
    bathrooms: 4,
    area: 3600,
    propertyType: "house",
    status: "available",
    address: { street: "5 Desert Bloom Rd", city: "Tucson", state: "AZ", zipcode: "85701", country: "USA" },
    location: { type: "Point", coordinates: [-110.9747, 32.2226] },
    amenities: ["Pool", "Solar Panels", "Courtyard", "Mountain View", "Sustainable Design"],
    isFeatured: true,
    meta: { furnished: false, yearBuilt: 2021 }
  },
  {
    title: "Waterfront Condo with Marina Access",
    description: "Beautiful waterfront condo with direct marina access. Panoramic water views from every room. Gourmet kitchen, master suite with water view, and a private balcony. Marina slip included.",
    price: 890000,
    bedrooms: 3,
    bathrooms: 2,
    area: 1800,
    propertyType: "condo",
    status: "available",
    address: { street: "1 Harbor Blvd", city: "San Diego", state: "CA", zipcode: "92101", country: "USA" },
    location: { type: "Point", coordinates: [-117.1611, 32.7157] },
    amenities: ["Marina Slip", "Water View", "Pool", "Gym", "Boat Storage"],
    isFeatured: false,
    meta: { furnished: false, yearBuilt: 2014 }
  },
  {
    title: "Converted Church Loft",
    description: "Spectacular conversion of a historic church into a one-of-a-kind home. Soaring arched ceilings, stained glass windows, and a mezzanine bedroom. Modern kitchen and bath blend seamlessly with original features.",
    price: 1100000,
    bedrooms: 3,
    bathrooms: 2,
    area: 3400,
    propertyType: "other",
    status: "available",
    address: { street: "777 Sanctuary Way", city: "Minneapolis", state: "MN", zipcode: "55401", country: "USA" },
    location: { type: "Point", coordinates: [-93.265, 44.9778] },
    amenities: ["Stained Glass", "High Ceilings", "Parking", "Garden"],
    isFeatured: false,
    meta: { furnished: false, yearBuilt: 1910 }
  },
  {
    title: "New Construction Apartment",
    description: "Brand-new apartment building with modern finishes throughout. Quartz countertops, soft-close cabinets, tile backsplash, and luxury vinyl plank flooring. Building has gym, co-working, and roof deck.",
    price: 480000,
    bedrooms: 1,
    bathrooms: 1,
    area: 700,
    propertyType: "apartment",
    status: "available",
    address: { street: "100 New Dawn Ct", city: "Dallas", state: "TX", zipcode: "75201", country: "USA" },
    location: { type: "Point", coordinates: [-96.797, 32.7767] },
    amenities: ["Gym", "Co-Working", "Roof Deck", "Pet Spa", "Package Room"],
    isFeatured: false,
    meta: { furnished: false, yearBuilt: 2024 }
  },
  {
    title: "Mountaintop Lodge with Panoramic Views",
    description: "Spectacular mountaintop lodge with 360-degree views. Great room with floor-to-ceiling stone fireplace, gourmet kitchen, game room, and a wraparound deck. Perfect for entertaining or a family retreat.",
    price: 2800000,
    bedrooms: 6,
    bathrooms: 5,
    area: 5500,
    propertyType: "house",
    status: "available",
    address: { street: "10 Summit Peak Rd", city: "Park City", state: "UT", zipcode: "84060", country: "USA" },
    location: { type: "Point", coordinates: [-111.4982, 40.6461] },
    amenities: ["Panoramic View", "Game Room", "Hot Tub", "Home Theater", "Wine Cellar"],
    isFeatured: true,
    meta: { furnished: true, yearBuilt: 2010 }
  },
  {
    title: "Restaurant Space with Liquor License",
    description: "Turnkey restaurant space in a high-traffic area. Fully equipped commercial kitchen, dining room seating 80, full bar, and outdoor patio. Existing liquor license included. Current lease available.",
    price: 950000,
    bedrooms: 0,
    bathrooms: 3,
    area: 2800,
    propertyType: "commercial",
    status: "available",
    address: { street: "42 Eatery Row", city: "New Orleans", state: "LA", zipcode: "70112", country: "USA" },
    location: { type: "Point", coordinates: [-90.0715, 29.9511] },
    amenities: ["Liquor License", "Commercial Kitchen", "Patio", "Parking Lot"],
    isFeatured: false,
    meta: { furnished: true, yearBuilt: 2002 }
  },
  {
    title: "Farmhouse with Acreage",
    description: "Charming farmhouse on 10 fertile acres. Updated home with country kitchen, wrap-around porch, and a basement. Property includes a barn, chicken coop, fenced pasture, and a small orchard.",
    price: 550000,
    bedrooms: 3,
    bathrooms: 2,
    area: 2000,
    propertyType: "house",
    status: "available",
    address: { street: "66 Country Rd", city: "Boulder", state: "CO", zipcode: "80301", country: "USA" },
    location: { type: "Point", coordinates: [-105.2705, 40.015] },
    amenities: ["Barn", "Orchard", "Pasture", "Garden", "Mountain View"],
    isFeatured: false,
    meta: { furnished: false, yearBuilt: 1920 }
  },
  {
    title: "Mediterranean Villa with Courtyard",
    description: "Beautiful Mediterranean-style villa with a central courtyard and fountain. Terracotta floors, arched doorways, and a chef's kitchen. Resort-style backyard with pool, spa, and outdoor fireplace.",
    price: 2100000,
    bedrooms: 5,
    bathrooms: 4,
    area: 4800,
    propertyType: "villa",
    status: "available",
    address: { street: "888 Mediterranean Ave", city: "Santa Barbara", state: "CA", zipcode: "93101", country: "USA" },
    location: { type: "Point", coordinates: [-119.6982, 34.4208] },
    amenities: ["Pool", "Courtyard", "Outdoor Fireplace", "Mountain View", "Wine Cellar"],
    isFeatured: true,
    meta: { furnished: true, yearBuilt: 2006 }
  },
  {
    title: "Affordable Apartment Complex",
    description: "12-unit apartment building with steady occupancy. Mix of 1 and 2-bedroom units. On-site laundry, off-street parking, and a common courtyard. Strong cash flow with room to increase rents.",
    price: 1800000,
    bedrooms: 18,
    bathrooms: 12,
    area: 10000,
    propertyType: "apartment",
    status: "rented",
    address: { street: "500 Rental Row", city: "Cleveland", state: "OH", zipcode: "44101", country: "USA" },
    location: { type: "Point", coordinates: [-81.6944, 41.4993] },
    amenities: ["Laundry", "Parking", "Courtyard", "Storage Units"],
    isFeatured: false,
    meta: { furnished: false, yearBuilt: 1980 }
  },
  {
    title: "Rustic Log Cabin",
    description: "Handcrafted log cabin on 5 wooded acres. Full logs with dovetail corners, a massive stone fireplace, loft bedrooms, and a screened porch. Perfect weekend getaway or full-time residence.",
    price: 425000,
    bedrooms: 3,
    bathrooms: 2,
    area: 1800,
    propertyType: "house",
    status: "available",
    address: { street: "22 Timber Ln", city: "Asheville", state: "NC", zipcode: "28801", country: "USA" },
    location: { type: "Point", coordinates: [-82.5515, 35.5951] },
    amenities: ["Fireplace", "Screened Porch", "Wooded Lot", "Mountain View"],
    isFeatured: false,
    meta: { furnished: true, yearBuilt: 2005 }
  },
  {
    title: "Corner Store with Upstairs Residence",
    description: "Historic corner store with a 2-bedroom apartment upstairs. Commercial space on the ground floor with high visibility. Apartment features original tin ceiling, exposed brick, and a roof terrace.",
    price: 675000,
    bedrooms: 2,
    bathrooms: 2,
    area: 2200,
    propertyType: "commercial",
    status: "available",
    address: { street: "1 Corner Sq", city: "Charleston", state: "SC", zipcode: "29401", country: "USA" },
    location: { type: "Point", coordinates: [-79.9311, 32.7765] },
    amenities: ["Storefront", "Residential Unit", "Roof Terrace", "Storage"],
    isFeatured: false,
    meta: { furnished: false, yearBuilt: 1890 }
  },
  {
    title: "Eco-Friendly Tiny House",
    description: "Beautifully designed tiny house on wheels with net-zero energy. Solar panels, composting toilet, rainwater collection, and a loft bedroom. Efficient use of space with custom built-ins. Park included.",
    price: 120000,
    bedrooms: 1,
    bathrooms: 1,
    area: 280,
    propertyType: "house",
    status: "available",
    address: { street: "88 Green Way", city: "Eugene", state: "OR", zipcode: "97401", country: "USA" },
    location: { type: "Point", coordinates: [-123.0868, 44.0521] },
    amenities: ["Solar", "Composting Toilet", "Rainwater System", "Off-Grid Capable"],
    isFeatured: false,
    meta: { furnished: true, yearBuilt: 2023 }
  },
  {
    title: "Luxury Apartment in Trendy Neighborhood",
    description: "Luxury apartment in the most sought-after neighborhood. Floor-to-ceiling windows, chef's kitchen with waterfall island, spa bathroom, and custom closet system. Steps from nightlife and dining.",
    price: 580000,
    bedrooms: 2,
    bathrooms: 2,
    area: 1050,
    propertyType: "apartment",
    status: "available",
    address: { street: "200 Trendy Blvd", city: "Miami Beach", state: "FL", zipcode: "33139", country: "USA" },
    location: { type: "Point", coordinates: [-80.13, 25.7903] },
    amenities: ["Pool", "Gym", "Concierge", "Valet", "Beach Access"],
    isFeatured: true,
    meta: { furnished: true, yearBuilt: 2022 }
  },
  {
    title: "Warehouse Space for Manufacturing",
    description: "Large warehouse with 24-foot clearance, three loading docks, and heavy power capacity. Office space included. Located in an industrial park with easy truck access. Ideal for manufacturing or distribution.",
    price: 1500000,
    bedrooms: 0,
    bathrooms: 4,
    area: 25000,
    propertyType: "commercial",
    status: "available",
    address: { street: "500 Industrial Park", city: "Kansas City", state: "MO", zipcode: "64101", country: "USA" },
    location: { type: "Point", coordinates: [-94.5786, 39.0997] },
    amenities: ["Loading Docks", "High Clearance", "Heavy Power", "Office Space", "Security"],
    isFeatured: false,
    meta: { furnished: false, yearBuilt: 2010 }
  },
  {
    title: "Beach Cottage with Private Path",
    description: "Adorable beach cottage with a private path to the sand. Open-plan living, shiplap walls, and a sunroom. Outdoor shower, beach gear storage, and a wrap-around porch with swing. Fully furnished.",
    price: 550000,
    bedrooms: 2,
    bathrooms: 1,
    area: 900,
    propertyType: "house",
    status: "available",
    address: { street: "99 Sandy Bottom Rd", city: "Santa Monica", state: "CA", zipcode: "90401", country: "USA" },
    location: { type: "Point", coordinates: [-118.4912, 34.0195] },
    amenities: ["Beach Path", "Outdoor Shower", "Porch", "Sunroom", "Furnished"],
    isFeatured: false,
    meta: { furnished: true, yearBuilt: 1955 }
  },
  {
    title: "Medical Office Building",
    description: "Professional medical office building with 8 exam rooms, a reception area, and private offices. Located near the hospital district. Ample parking, elevator access, and updated HVAC system.",
    price: 2200000,
    bedrooms: 0,
    bathrooms: 6,
    area: 4500,
    propertyType: "commercial",
    status: "available",
    address: { street: "1 Health Center Dr", city: "Houston", state: "TX", zipcode: "77001", country: "USA" },
    location: { type: "Point", coordinates: [-95.3698, 29.7604] },
    amenities: ["Elevator", "Parking Lot", "Exam Rooms", "Reception", "Near Hospital"],
    isFeatured: false,
    meta: { furnished: true, yearBuilt: 2015 }
  },
  {
    title: "Colonial Revival Family Home",
    description: "Beautiful Colonial Revival home on a tree-lined street. Formal living and dining rooms, updated kitchen with breakfast nook, family room with fireplace, and a finished attic. Fenced backyard with patio.",
    price: 610000,
    bedrooms: 4,
    bathrooms: 3,
    area: 3000,
    propertyType: "house",
    status: "available",
    address: { street: "75 Colonial Dr", city: "Richmond", state: "VA", zipcode: "23219", country: "USA" },
    location: { type: "Point", coordinates: [-77.436, 37.5407] },
    amenities: ["Fireplace", "Patio", "Attic", "Hardwood Floors", "Fenced Yard"],
    isFeatured: false,
    meta: { furnished: false, yearBuilt: 1978 }
  },
  {
    title: "Ski-In/Ski-Out Condo",
    description: "Slopeside condo with ski-in/ski-out access. Beautifully furnished with a stone fireplace, bunk room, and a private hot tub on the deck. Underground parking and ski locker included.",
    price: 750000,
    bedrooms: 3,
    bathrooms: 2,
    area: 1400,
    propertyType: "condo",
    status: "available",
    address: { street: "15 Ski Trail", city: "Vail", state: "CO", zipcode: "81657", country: "USA" },
    location: { type: "Point", coordinates: [-106.3775, 39.6403] },
    amenities: ["Ski-In/Ski-Out", "Hot Tub", "Fireplace", "Underground Parking", "Ski Locker"],
    isFeatured: false,
    meta: { furnished: true, yearBuilt: 2013 }
  },
  {
    title: "Apartment with City View Balcony",
    description: "Bright apartment with a private balcony overlooking the city skyline. Open kitchen with breakfast bar, in-unit washer/dryer, and walk-in closet. Building features a resident lounge and courtyard.",
    price: 390000,
    bedrooms: 1,
    bathrooms: 1,
    area: 680,
    propertyType: "apartment",
    status: "available",
    address: { street: "300 Skyline Ave", city: "Denver", state: "CO", zipcode: "80202", country: "USA" },
    location: { type: "Point", coordinates: [-104.9903, 39.742] },
    amenities: ["Balcony", "In-Unit Laundry", "Lounge", "Courtyard", "Storage"],
    isFeatured: false,
    meta: { furnished: false, yearBuilt: 2019 }
  },
  {
    title: "Horse Property with Arena",
    description: "Complete horse facility on 15 acres. 8-stall barn with wash rack, tack room, and hay storage. Outdoor arena with footing, round pen, and fenced pastures. 4-bedroom farmhouse included.",
    price: 1200000,
    bedrooms: 4,
    bathrooms: 3,
    area: 3200,
    propertyType: "house",
    status: "available",
    address: { street: "2000 Equestrian Dr", city: "Lexington", state: "KY", zipcode: "40502", country: "USA" },
    location: { type: "Point", coordinates: [-84.5037, 38.0406] },
    amenities: ["Barn", "Arena", "Pastures", "Round Pen", "Tack Room"],
    isFeatured: false,
    meta: { furnished: false, yearBuilt: 2000 }
  },
  {
    title: "Penthouse Apartment with Wrap Terrace",
    description: "Exclusive penthouse with a wraparound terrace offering unobstructed views. Two master suites, a study, formal dining, and a gourmet kitchen with top-of-the-line appliances. Private elevator.",
    price: 4500000,
    bedrooms: 4,
    bathrooms: 4,
    area: 4000,
    propertyType: "apartment",
    status: "available",
    address: { street: "1 Billionaire Row", city: "New York", state: "NY", zipcode: "10019", country: "USA" },
    location: { type: "Point", coordinates: [-73.9787, 40.7648] },
    amenities: ["Private Elevator", "Wraparound Terrace", "Concierge", "Wine Room", "Library"],
    isFeatured: true,
    meta: { furnished: true, yearBuilt: 2020 }
  },
  {
    title: "Art Gallery with Loft",
    description: "Converted storefront art gallery with a spacious loft apartment upstairs. High ceilings, track lighting, and white walls for exhibition space. Loft has an open kitchen, exposed brick, and skylights.",
    price: 720000,
    bedrooms: 2,
    bathrooms: 2,
    area: 2600,
    propertyType: "commercial",
    status: "available",
    address: { street: "50 Arts District Ln", city: "Portland", state: "OR", zipcode: "97202", country: "USA" },
    location: { type: "Point", coordinates: [-122.6599, 45.5068] },
    amenities: ["Gallery Space", "Skylights", "Exposed Brick", "Storefront"],
    isFeatured: false,
    meta: { furnished: false, yearBuilt: 1915 }
  },
  {
    title: "Modern Townhouse with Rooftop Pool",
    description: "Sleek modern townhouse with a private rooftop pool. Glass walls, floating staircase, smart home system, and a two-car garage. Open-plan living with floor-to-ceiling sliding glass doors.",
    price: 1500000,
    bedrooms: 4,
    bathrooms: 4,
    area: 3500,
    propertyType: "townhouse",
    status: "available",
    address: { street: "99 Modern Ln", city: "Austin", state: "TX", zipcode: "73302", country: "USA" },
    location: { type: "Point", coordinates: [-97.7431, 30.2772] },
    amenities: ["Rooftop Pool", "Smart Home", "Garage", "Home Theater", "Wine Room"],
    isFeatured: true,
    meta: { furnished: false, yearBuilt: 2023 }
  },
  {
    title: "Duplex with Dual Income",
    description: "Well-maintained duplex with two 3-bedroom units. Both units recently renovated with new kitchens, bathrooms, and flooring. Fully occupied with below-market rents. Excellent investment opportunity.",
    price: 780000,
    bedrooms: 6,
    bathrooms: 4,
    area: 3600,
    propertyType: "house",
    status: "rented",
    address: { street: "123 Investment Ave", city: "Indianapolis", state: "IN", zipcode: "46201", country: "USA" },
    location: { type: "Point", coordinates: [-86.1581, 39.7684] },
    amenities: ["Two Units", "Laundry Hookups", "Off-Street Parking", "Yard"],
    isFeatured: false,
    meta: { furnished: false, yearBuilt: 1995 }
  },
  {
    title: "Wine Country Estate",
    description: "Magnificent estate in the heart of wine country. 6-bedroom main house, separate guest house, and a wine cave. Vineyard with 5 acres of Cabernet Sauvignon. Infinity pool overlooking the valley.",
    price: 5800000,
    bedrooms: 6,
    bathrooms: 7,
    area: 7000,
    propertyType: "villa",
    status: "available",
    address: { street: "10 Vineyard Rd", city: "Napa", state: "CA", zipcode: "94558", country: "USA" },
    location: { type: "Point", coordinates: [-122.2865, 38.2975] },
    amenities: ["Vineyard", "Wine Cave", "Infinity Pool", "Guest House", "Valley View"],
    isFeatured: true,
    meta: { furnished: true, yearBuilt: 2015 }
  },
  {
    title: "Retail Space in Shopping Center",
    description: "Prime retail space in a established shopping center. High visibility with highway frontage. 1,500 sq ft with restroom and storage room. Great for restaurant, retail, or service business.",
    price: 550000,
    bedrooms: 0,
    bathrooms: 1,
    area: 1500,
    propertyType: "commercial",
    status: "available",
    address: { street: "800 Shopping Center Dr", city: "Orlando", state: "FL", zipcode: "32801", country: "USA" },
    location: { type: "Point", coordinates: [-81.3792, 28.5383] },
    amenities: ["High Visibility", "Highway Frontage", "Parking Lot", "Storage"],
    isFeatured: false,
    meta: { furnished: false, yearBuilt: 2008 }
  },
  {
    title: "Victorian Painted Lady",
    description: "Stunning Victorian home with original Queen Anne architecture. Three stories with a tower room, wrap-around porch, stained glass windows, and period woodwork. Modern kitchen and baths added.",
    price: 1350000,
    bedrooms: 5,
    bathrooms: 4,
    area: 4200,
    propertyType: "house",
    status: "available",
    address: { street: "777 Victorian Ave", city: "San Francisco", state: "CA", zipcode: "94102", country: "USA" },
    location: { type: "Point", coordinates: [-122.4194, 37.7749] },
    amenities: ["Stained Glass", "Wrap Porch", "Period Details", "Garden"],
    isFeatured: true,
    meta: { furnished: false, yearBuilt: 1895 }
  },
  {
    title: "Lakefront Condo with Dock",
    description: "Beautiful condo on the lake with a private dock. Open-concept living with lake views from every room. Updated kitchen with granite counters, and a master suite with lake-view balcony.",
    price: 480000,
    bedrooms: 2,
    bathrooms: 2,
    area: 1200,
    propertyType: "condo",
    status: "available",
    address: { street: "400 Lakeshore Dr", city: "Chicago", state: "IL", zipcode: "60611", country: "USA" },
    location: { type: "Point", coordinates: [-87.6298, 41.8917] },
    amenities: ["Dock", "Lake View", "Balcony", "Pool", "Gym"],
    isFeatured: false,
    meta: { furnished: false, yearBuilt: 2012 }
  },
  {
    title: "Building Lot with Permits Approved",
    description: "Vacant building lot in a desirable neighborhood. All permits approved for a 3,000 sq ft custom home. Survey, soil tests, and architectural plans included. Ready to build immediately.",
    price: 225000,
    bedrooms: 0,
    bathrooms: 0,
    area: 12000,
    propertyType: "land",
    status: "available",
    address: { street: "50 Build Ready Ct", city: "Seattle", state: "WA", zipcode: "98102", country: "USA" },
    location: { type: "Point", coordinates: [-122.322, 47.622] },
    amenities: ["Permits Approved", "Plans Included", "Utilities Available"],
    isFeatured: false,
    meta: { yearBuilt: null }
  },
  {
    title: "Artist's Live-Work Studio",
    description: "Creative live-work space with a large studio flooded with north light. Open mezzanine bedroom, kitchenette, and a bathroom with soaking tub. High ceilings and polished concrete floors.",
    price: 350000,
    bedrooms: 1,
    bathrooms: 1,
    area: 1200,
    propertyType: "other",
    status: "available",
    address: { street: "77 Creative Way", city: "Los Angeles", state: "CA", zipcode: "90014", country: "USA" },
    location: { type: "Point", coordinates: [-118.2505, 34.04] },
    amenities: ["North Light", "High Ceilings", "Loading Area", "Storefront Window"],
    isFeatured: false,
    meta: { furnished: false, yearBuilt: 2001 }
  },
  {
    title: "Mountain View Apartment",
    description: "Apartment with stunning mountain views from every window. Updated kitchen with quartz counters, new bathroom, and hardwood floors. Building features a community garden and bike storage.",
    price: 375000,
    bedrooms: 2,
    bathrooms: 1,
    area: 850,
    propertyType: "apartment",
    status: "available",
    address: { street: "600 Mountain Ave", city: "Salt Lake City", state: "UT", zipcode: "84101", country: "USA" },
    location: { type: "Point", coordinates: [-111.891, 40.7608] },
    amenities: ["Mountain View", "Garden", "Bike Storage", "Laundry"],
    isFeatured: false,
    meta: { furnished: false, yearBuilt: 2017 }
  },
  {
    title: "Spanish Colonial Estate",
    description: "Magnificent Spanish Colonial estate with a tile roof, arched loggia, and a central courtyard with fountain. Hand-painted tiles, wrought iron details, and a saltwater pool. Guest casita included.",
    price: 3400000,
    bedrooms: 5,
    bathrooms: 5,
    area: 5500,
    propertyType: "villa",
    status: "available",
    address: { street: "1 Hacienda Way", city: "Santa Fe", state: "NM", zipcode: "87501", country: "USA" },
    location: { type: "Point", coordinates: [-105.9378, 35.687] },
    amenities: ["Pool", "Courtyard", "Guest Casita", "Mountain View", "Garden"],
    isFeatured: true,
    meta: { furnished: true, yearBuilt: 1935 }
  },
  {
    title: "Triplex Investment Property",
    description: "Three-unit residential building with great rental history. One 2-bedroom and two 1-bedroom units. All units recently updated. On-site laundry and shared backyard. Low vacancy rate in the area.",
    price: 920000,
    bedrooms: 4,
    bathrooms: 3,
    area: 3200,
    propertyType: "house",
    status: "rented",
    address: { street: "300 Triplex Ave", city: "Milwaukee", state: "WI", zipcode: "53201", country: "USA" },
    location: { type: "Point", coordinates: [-87.9065, 43.0389] },
    amenities: ["Laundry", "Backyard", "Storage", "Street Parking"],
    isFeatured: false,
    meta: { furnished: false, yearBuilt: 1988 }
  },
  {
    title: "Ocean Bluff Estate",
    description: "Spectacular estate perched on an ocean bluff with unobstructed Pacific views. Floor-to-ceiling windows, a great room with fireplace, gourmet kitchen, and a master suite with ocean-view soaking tub.",
    price: 6200000,
    bedrooms: 5,
    bathrooms: 6,
    area: 6000,
    propertyType: "house",
    status: "available",
    address: { street: "1 Bluff Way", city: "Carmel", state: "CA", zipcode: "93921", country: "USA" },
    location: { type: "Point", coordinates: [-121.9233, 36.5552] },
    amenities: ["Ocean View", "Infinity Pool", "Home Theater", "Wine Room", "Private Beach Access"],
    isFeatured: true,
    meta: { furnished: true, yearBuilt: 2018 }
  },
  {
    title: "Office Space in Tech Hub",
    description: "Modern office space in a premier tech hub location. Open floor plan with glass-walled offices, a break room, and conference rooms. Fiber internet installed. Ideal for startups or growing teams.",
    price: 850000,
    bedrooms: 0,
    bathrooms: 2,
    area: 2000,
    propertyType: "commercial",
    status: "available",
    address: { street: "500 Innovation Dr", city: "Palo Alto", state: "CA", zipcode: "94301", country: "USA" },
    location: { type: "Point", coordinates: [-122.143, 37.4419] },
    amenities: ["Fiber Internet", "Conference Rooms", "Kitchen", "Parking", "24/7 Access"],
    isFeatured: false,
    meta: { furnished: true, yearBuilt: 2020 }
  },
  {
    title: "Ranch-Style Home with Pool",
    description: "Spacious ranch-style home with a resort-style backyard. In-ground pool with waterfall, covered patio with outdoor kitchen, and a fire pit. Open interior with a great room and master suite split.",
    price: 520000,
    bedrooms: 3,
    bathrooms: 2,
    area: 2000,
    propertyType: "house",
    status: "available",
    address: { street: "75 Rancho Rd", city: "Las Vegas", state: "NV", zipcode: "89101", country: "USA" },
    location: { type: "Point", coordinates: [-115.1398, 36.1699] },
    amenities: ["Pool", "Outdoor Kitchen", "Fire Pit", "Covered Patio", "Mountain View"],
    isFeatured: false,
    meta: { furnished: false, yearBuilt: 2002 }
  },
  {
    title: "Apartment with Mountain Views",
    description: "Top-floor apartment with panoramic mountain views. Updated kitchen, new flooring, and a private balcony. Building has a fitness center, rooftop lounge, and assigned parking spot.",
    price: 410000,
    bedrooms: 2,
    bathrooms: 2,
    area: 950,
    propertyType: "apartment",
    status: "available",
    address: { street: "450 Summit Ridge", city: "Boise", state: "ID", zipcode: "83701", country: "USA" },
    location: { type: "Point", coordinates: [-116.2023, 43.615] },
    amenities: ["Gym", "Rooftop Lounge", "Balcony", "Parking", "Mountain View"],
    isFeatured: false,
    meta: { furnished: false, yearBuilt: 2021 }
  },
  {
    title: "Treehouse Cabin in the Woods",
    description: "Magical treehouse cabin suspended among old-growth trees. Wraparound deck with forest views, outdoor shower, wood-burning stove, and a loft bedroom. Off-grid with solar power and rainwater catchment.",
    price: 280000,
    bedrooms: 1,
    bathrooms: 1,
    area: 400,
    propertyType: "other",
    status: "available",
    address: { street: "1 Forest Canopy", city: "Sedona", state: "AZ", zipcode: "86336", country: "USA" },
    location: { type: "Point", coordinates: [-111.7612, 34.8697] },
    amenities: ["Treehouse", "Solar", "Outdoor Shower", "Forest View", "Wood Stove"],
    isFeatured: true,
    meta: { furnished: true, yearBuilt: 2022 }
  },
  {
    title: "Starter Condo with Low HOA",
    description: "Affordable condo perfect for first-time buyers. Open layout with updated kitchen, new bathroom vanity, and fresh paint. Low monthly HOA includes water, trash, and building maintenance.",
    price: 215000,
    bedrooms: 1,
    bathrooms: 1,
    area: 600,
    propertyType: "condo",
    status: "available",
    address: { street: "250 Budget Ave", city: "Tampa", state: "FL", zipcode: "33601", country: "USA" },
    location: { type: "Point", coordinates: [-82.4572, 27.9506] },
    amenities: ["Pool", "Laundry", "Assigned Parking", "Storage Locker"],
    isFeatured: false,
    meta: { furnished: false, yearBuilt: 1998 }
  },
  {
    title: "Mixed-Use Building with Retail",
    description: "Mixed-use building with ground-floor retail and two residential units above. Retail space leased to a popular coffee shop. Both apartments renovated and occupied. Strong cash flow investment.",
    price: 1250000,
    bedrooms: 4,
    bathrooms: 3,
    area: 4000,
    propertyType: "commercial",
    status: "rented",
    address: { street: "1 Main & Broadway", city: "Nashville", state: "TN", zipcode: "37202", country: "USA" },
    location: { type: "Point", coordinates: [-86.782, 36.1667] },
    amenities: ["Retail Space", "Residential Units", "Stable Income", "Prime Location"],
    isFeatured: false,
    meta: { furnished: false, yearBuilt: 1930 }
  },
  {
    title: "Hilltop Estate with Guest House",
    description: "Hilltop estate with sweeping valley views. Main house features 5 bedrooms, a library, wine cellar, and a gourmet kitchen. Guest house with 2 bedrooms. Infinity pool, tennis court, and helipad.",
    price: 7500000,
    bedrooms: 7,
    bathrooms: 8,
    area: 8500,
    propertyType: "villa",
    status: "available",
    address: { street: "1 Hilltop Dr", city: "Beverly Hills", state: "CA", zipcode: "90210", country: "USA" },
    location: { type: "Point", coordinates: [-118.4004, 34.0736] },
    amenities: ["Infinity Pool", "Tennis Court", "Helipad", "Guest House", "Valley View"],
    isFeatured: true,
    meta: { furnished: true, yearBuilt: 2016 }
  },
  {
    title: "Fourplex in Growing Neighborhood",
    description: "Four-unit apartment building in a rapidly growing neighborhood. Mix of 1 and 2-bedroom units. Laundry facility, off-street parking, and separate utility meters. Below-market rents with upside potential.",
    price: 1100000,
    bedrooms: 6,
    bathrooms: 4,
    area: 4000,
    propertyType: "apartment",
    status: "rented",
    address: { street: "123 Growth Blvd", city: "Charlotte", state: "NC", zipcode: "28201", country: "USA" },
    location: { type: "Point", coordinates: [-80.8431, 35.2271] },
    amenities: ["Laundry", "Parking", "Separate Meters", "Storage"],
    isFeatured: false,
    meta: { furnished: false, yearBuilt: 2005 }
  },
  {
    title: "Garden-Level Apartment",
    description: "Garden-level apartment with direct access to a shared garden. Bright and airy with an updated kitchen, exposed brick accent wall, and good closet space. Pet-friendly building. Available immediately.",
    price: 285000,
    bedrooms: 1,
    bathrooms: 1,
    area: 650,
    propertyType: "apartment",
    status: "available",
    address: { street: "42 Garden Ln", city: "Atlanta", state: "GA", zipcode: "30302", country: "USA" },
    location: { type: "Point", coordinates: [-84.386, 33.742] },
    amenities: ["Garden Access", "Pet Friendly", "Laundry", "Storage"],
    isFeatured: false,
    meta: { furnished: false, yearBuilt: 2011 }
  },
  {
    title: "Storage Facility Business",
    description: "Self-storage facility with 200 units on 5 acres. High occupancy rate with waiting list. On-site manager's office and security system. Expansion potential with additional land available.",
    price: 3200000,
    bedrooms: 0,
    bathrooms: 2,
    area: 90000,
    propertyType: "commercial",
    status: "available",
    address: { street: "500 Storage Way", city: "Riverside", state: "CA", zipcode: "92501", country: "USA" },
    location: { type: "Point", coordinates: [-117.3962, 33.9533] },
    amenities: ["Security System", "Manager Office", "Expansion Potential", "High Occupancy"],
    isFeatured: false,
    meta: { furnished: false, yearBuilt: 2010 }
  },
  {
    title: "Contemporary Home with Pool House",
    description: "Sleek contemporary home with a separate pool house. Main house has 4 bedrooms, a chef's kitchen, and a great room with 20-foot ceilings. Pool house features a full bath and wet bar.",
    price: 1850000,
    bedrooms: 5,
    bathrooms: 5,
    area: 4500,
    propertyType: "house",
    status: "available",
    address: { street: "900 Contemporary Ct", city: "Dallas", state: "TX", zipcode: "75202", country: "USA" },
    location: { type: "Point", coordinates: [-96.795, 32.78] },
    amenities: ["Pool House", "Pool", "Outdoor Kitchen", "Smart Home", "Garage"],
    isFeatured: true,
    meta: { furnished: false, yearBuilt: 2022 }
  },
  {
    title: "Bungalow Court with 3 Units",
    description: "Charming bungalow court with three detached units around a central garden. Each unit has 2 bedrooms and 1 bathroom. Great for multifamily living or rental income. Laundry and parking included.",
    price: 890000,
    bedrooms: 6,
    bathrooms: 3,
    area: 2800,
    propertyType: "house",
    status: "rented",
    address: { street: "555 Bungalow Ct", city: "San Diego", state: "CA", zipcode: "92102", country: "USA" },
    location: { type: "Point", coordinates: [-117.157, 32.71] },
    amenities: ["Garden", "Laundry", "Parking", "Detached Units"],
    isFeatured: false,
    meta: { furnished: false, yearBuilt: 1945 }
  },
  {
    title: "Mountain Cabin with River Access",
    description: "Log cabin on the river with private fishing access. Two stone fireplaces, a screen porch, and a hot tub on the deck. Furnished with rustic mountain decor. Great vacation rental potential.",
    price: 465000,
    bedrooms: 3,
    bathrooms: 2,
    area: 1600,
    propertyType: "house",
    status: "available",
    address: { street: "88 River Run Rd", city: "Durango", state: "CO", zipcode: "81301", country: "USA" },
    location: { type: "Point", coordinates: [-107.8802, 37.2753] },
    amenities: ["River Access", "Hot Tub", "Fireplace", "Screen Porch", "Furnished"],
    isFeatured: false,
    meta: { furnished: true, yearBuilt: 2006 }
  },
  {
    title: "Downtown Loft with Parking",
    description: "Industrial loft in a converted warehouse in the downtown core. Exposed brick, concrete columns, and large windows. Gourmet kitchen, spa-like bath, and one deeded parking spot included.",
    price: 510000,
    bedrooms: 1,
    bathrooms: 1,
    area: 1000,
    propertyType: "apartment",
    status: "available",
    address: { street: "100 Downtown Loop", city: "Portland", state: "OR", zipcode: "97203", country: "USA" },
    location: { type: "Point", coordinates: [-122.674, 45.52] },
    amenities: ["Parking", "Exposed Brick", "High Ceilings", "Gym", "Rooftop"],
    isFeatured: false,
    meta: { furnished: false, yearBuilt: 1920 }
  },
  {
    title: "Farmland with Irrigation",
    description: "100 acres of prime farmland with an established irrigation system. Currently planted with corn and soybeans. Fertile soil with excellent drainage. Includes equipment shed and grain bins.",
    price: 850000,
    bedrooms: 0,
    bathrooms: 0,
    area: 4356000,
    propertyType: "land",
    status: "available",
    address: { street: "1 Farm to Market Rd", city: "Des Moines", state: "IA", zipcode: "50301", country: "USA" },
    location: { type: "Point", coordinates: [-93.6091, 41.6005] },
    amenities: ["Irrigation", "Equipment Shed", "Grain Bins", "Fertile Soil"],
    isFeatured: false,
    meta: { yearBuilt: null }
  },
  {
    title: "Luxury Home with Chef's Kitchen",
    description: "Dream home for the avid cook with a professional-grade chef's kitchen featuring double ovens, a 6-burner gas range, warming drawer, and a walk-in pantry. Open to a great room with backyard views.",
    price: 950000,
    bedrooms: 4,
    bathrooms: 3,
    area: 3500,
    propertyType: "house",
    status: "available",
    address: { street: "200 Gourmet Way", city: "Denver", state: "CO", zipcode: "80203", country: "USA" },
    location: { type: "Point", coordinates: [-104.987, 39.735] },
    amenities: ["Chef's Kitchen", "Wine Storage", "Deck", "Mountain View", "Garage"],
    isFeatured: false,
    meta: { furnished: false, yearBuilt: 2019 }
  },
  {
    title: "Office Condo in Business Park",
    description: "Professional office condo in a well-maintained business park. Private entrance, reception area, 3 private offices, a break room, and restrooms. Ample parking and easy highway access.",
    price: 380000,
    bedrooms: 0,
    bathrooms: 2,
    area: 1400,
    propertyType: "commercial",
    status: "available",
    address: { street: "300 Business Park Dr", city: "Phoenix", state: "AZ", zipcode: "85002", country: "USA" },
    location: { type: "Point", coordinates: [-112.078, 33.45] },
    amenities: ["Private Entrance", "Parking", "Highway Access", "Storage"],
    isFeatured: false,
    meta: { furnished: false, yearBuilt: 2012 }
  },
  {
    title: "Condo with Lake View",
    description: "Beautiful condo overlooking a private lake. Updated kitchen with granite counters, new flooring, and a master suite with lake view. Community amenities include pool, tennis, and clubhouse.",
    price: 320000,
    bedrooms: 2,
    bathrooms: 2,
    area: 1100,
    propertyType: "condo",
    status: "available",
    address: { street: "75 Lake View Dr", city: "Minneapolis", state: "MN", zipcode: "55402", country: "USA" },
    location: { type: "Point", coordinates: [-93.27, 44.97] },
    amenities: ["Lake View", "Pool", "Tennis", "Clubhouse", "Balcony"],
    isFeatured: false,
    meta: { furnished: false, yearBuilt: 2007 }
  },
  {
    title: "Eco-Community Home",
    description: "Energy-efficient home in an eco-conscious community. Solar panels, geothermal heating, rainwater harvesting, and a vegetable garden. Open floor plan with sustainable materials throughout.",
    price: 520000,
    bedrooms: 3,
    bathrooms: 2,
    area: 2000,
    propertyType: "house",
    status: "available",
    address: { street: "100 Green Living Dr", city: "Burlington", state: "VT", zipcode: "05401", country: "USA" },
    location: { type: "Point", coordinates: [-73.2121, 44.4759] },
    amenities: ["Solar", "Geothermal", "Rainwater Harvesting", "Garden", "Community"],
    isFeatured: false,
    meta: { furnished: false, yearBuilt: 2023 }
  },
  {
    title: "Motor Court with 8 Garages",
    description: "Unique motor court property with 8 oversized garage bays and a 2-bedroom apartment. Perfect for car enthusiasts or as a workshop. Each bay has an automatic door and 220V power.",
    price: 650000,
    bedrooms: 2,
    bathrooms: 1,
    area: 5000,
    propertyType: "other",
    status: "available",
    address: { street: "500 Gearhead Ave", city: "Detroit", state: "MI", zipcode: "48202", country: "USA" },
    location: { type: "Point", coordinates: [-83.045, 42.335] },
    amenities: ["8 Garages", "220V Power", "Workspace", "Living Quarters"],
    isFeatured: false,
    meta: { furnished: false, yearBuilt: 2015 }
  },
  {
    title: "Senior Living Condo",
    description: "Ground-floor condo in a 55+ community. Wide doorways, walk-in shower, and grab bars. Open layout with a den. Community offers meals, transportation, and social activities. Low-maintenance living.",
    price: 295000,
    bedrooms: 2,
    bathrooms: 2,
    area: 1100,
    propertyType: "condo",
    status: "available",
    address: { street: "1 Golden Years Dr", city: "Phoenix", state: "AZ", zipcode: "85003", country: "USA" },
    location: { type: "Point", coordinates: [-112.08, 33.44] },
    amenities: ["Ground Floor", "Walk-In Shower", "Community Meals", "Transportation"],
    isFeatured: false,
    meta: { furnished: false, yearBuilt: 2018 }
  },
  {
    title: "Micro-Apartment in Tech Hub",
    description: "Efficient micro-apartment designed for maximum space utilization. Murphy bed, fold-down desk, integrated storage, and a compact kitchen. Walking distance to all major tech headquarters.",
    price: 195000,
    bedrooms: 0,
    bathrooms: 1,
    area: 350,
    propertyType: "apartment",
    status: "available",
    address: { street: "1 Tech Square", city: "San Francisco", state: "CA", zipcode: "94107", country: "USA" },
    location: { type: "Point", coordinates: [-122.396, 37.775] },
    amenities: ["Furnished", "In-Unit Laundry", "Rooftop", "Bike Room"],
    isFeatured: false,
    meta: { furnished: true, yearBuilt: 2020 }
  },
  {
    title: "Organic Vineyard with Tasting Room",
    description: "Established organic vineyard with 20 acres of producing vines. Includes a charming tasting room, barrel room, and a 3-bedroom farmhouse. Certified organic. Award-winning wine history.",
    price: 2200000,
    bedrooms: 3,
    bathrooms: 2,
    area: 2200,
    propertyType: "commercial",
    status: "available",
    address: { street: "99 Organic Vines Rd", city: "Sonoma", state: "CA", zipcode: "95476", country: "USA" },
    location: { type: "Point", coordinates: [-122.456, 38.292] },
    amenities: ["Tasting Room", "Wine Cave", "Organic Certified", "Farmhouse"],
    isFeatured: true,
    meta: { furnished: false, yearBuilt: 1995 }
  },
  {
    title: "Split-Level Home with In-Law Suite",
    description: "Split-level home with a separate in-law suite. Main level has 3 bedrooms, formal living and dining. Lower level has a full apartment with kitchen, bedroom, and private entrance. Ideal for multi-gen.",
    price: 580000,
    bedrooms: 4,
    bathrooms: 3,
    area: 2800,
    propertyType: "house",
    status: "available",
    address: { street: "150 Split Level Ct", city: "St. Louis", state: "MO", zipcode: "63101", country: "USA" },
    location: { type: "Point", coordinates: [-90.1994, 38.627] },
    amenities: ["In-Law Suite", "Private Entrance", "Deck", "Fenced Yard", "Garage"],
    isFeatured: false,
    meta: { furnished: false, yearBuilt: 1975 }
  },
  {
    title: "Carriage House with Apartment",
    description: "Historic carriage house with a renovated apartment above. Two-car garage on the ground floor. Upstairs apartment features a loft bedroom, full kitchen, and a rooftop deck with city views.",
    price: 780000,
    bedrooms: 1,
    bathrooms: 1,
    area: 1800,
    propertyType: "other",
    status: "available",
    address: { street: "200 Carriage Way", city: "Savannah", state: "GA", zipcode: "31401", country: "USA" },
    location: { type: "Point", coordinates: [-81.0998, 32.0809] },
    amenities: ["Garage", "Rooftop Deck", "Historic", "Cobblestone Street"],
    isFeatured: false,
    meta: { furnished: false, yearBuilt: 1905 }
  },
  {
    title: "New Development Land Parcel",
    description: "Prime development land zoned for mixed-use. 5 acres in a high-growth corridor. Environmental studies completed. Ideal for a residential or commercial development project. Utilities at the street.",
    price: 1200000,
    bedrooms: 0,
    bathrooms: 0,
    area: 217800,
    propertyType: "land",
    status: "available",
    address: { street: "50 Development Ave", city: "Orlando", state: "FL", zipcode: "32802", country: "USA" },
    location: { type: "Point", coordinates: [-81.38, 28.54] },
    amenities: ["Zoned Mixed-Use", "Utilities", "High Growth Area"],
    isFeatured: false,
    meta: { yearBuilt: null }
  },
  {
    title: "Penthouse with Wraparound Terrace",
    description: "Stunning penthouse with a wraparound terrace and outdoor kitchen. Interior features include a grand foyer, formal dining, chef's kitchen, and a library. Panoramic ocean and city views.",
    price: 5200000,
    bedrooms: 4,
    bathrooms: 5,
    area: 4800,
    propertyType: "condo",
    status: "available",
    address: { street: "1 Ocean Tower", city: "Miami Beach", state: "FL", zipcode: "33140", country: "USA" },
    location: { type: "Point", coordinates: [-80.13, 25.79] },
    amenities: ["Wraparound Terrace", "Outdoor Kitchen", "Concierge", "Spa", "Pool"],
    isFeatured: true,
    meta: { furnished: true, yearBuilt: 2021 }
  },
  {
    title: "Apartment Near Transit Hub",
    description: "Convenient apartment steps from the subway and bus terminal. Updated with stainless steel appliances, quartz counters, and vinyl plank flooring. Building has a gym and rooftop deck.",
    price: 350000,
    bedrooms: 1,
    bathrooms: 1,
    area: 650,
    propertyType: "apartment",
    status: "available",
    address: { street: "50 Transit Plaza", city: "Jersey City", state: "NJ", zipcode: "07302", country: "USA" },
    location: { type: "Point", coordinates: [-74.0776, 40.7282] },
    amenities: ["Near Transit", "Gym", "Rooftop", "Laundry"],
    isFeatured: false,
    meta: { furnished: false, yearBuilt: 2018 }
  },
  {
    title: "Craftsman Home with Mountain View",
    description: "Beautiful craftsman home with mountain views from the front porch. Stone fireplace, built-in bookcases, a sunroom, and a finished basement. Landscaped yard with perennial gardens and a pond.",
    price: 640000,
    bedrooms: 3,
    bathrooms: 2,
    area: 2400,
    propertyType: "house",
    status: "available",
    address: { street: "123 Craftsman Ln", city: "Spokane", state: "WA", zipcode: "99201", country: "USA" },
    location: { type: "Point", coordinates: [-117.426, 47.6588] },
    amenities: ["Mountain View", "Sunroom", "Garden", "Finished Basement", "Fireplace"],
    isFeatured: false,
    meta: { furnished: false, yearBuilt: 1992 }
  },
  {
    title: "Retail Kiosk in Mall",
    description: "High-traffic retail kiosk in a busy shopping mall. Perfect for jewelry, phone accessories, or food. Turnkey operation with display cases and storage. Flexible lease terms available.",
    price: 85000,
    bedrooms: 0,
    bathrooms: 0,
    area: 150,
    propertyType: "commercial",
    status: "available",
    address: { street: "1 Mall Blvd", city: "Paramus", state: "NJ", zipcode: "07652", country: "USA" },
    location: { type: "Point", coordinates: [-74.075, 40.916] },
    amenities: ["High Traffic", "Turnkey", "Display Cases", "Mall Hours"],
    isFeatured: false,
    meta: { furnished: true, yearBuilt: 2015 }
  },
  {
    title: "Converted Schoolhouse",
    description: "Unique conversion of a historic schoolhouse into a stunning residence. Classrooms transformed into bedrooms, the auditorium into a great room, and the gym into a home theater. Sweeping views.",
    price: 975000,
    bedrooms: 4,
    bathrooms: 3,
    area: 4000,
    propertyType: "other",
    status: "available",
    address: { street: "1 Schoolhouse Rd", city: "Hudson", state: "NY", zipcode: "12534", country: "USA" },
    location: { type: "Point", coordinates: [-73.7908, 42.2528] },
    amenities: ["High Ceilings", "Original Floors", "Gym", "Garden", "Parking"],
    isFeatured: false,
    meta: { furnished: false, yearBuilt: 1925 }
  },
  {
    title: "Water Park Hotel",
    description: "Hotel with an indoor water park on 10 acres. 80 rooms, conference center, restaurant, and full-service spa. Indoor and outdoor pools with water slides. Revenue history available. Turnkey operation.",
    price: 8500000,
    bedrooms: 80,
    bathrooms: 80,
    area: 45000,
    propertyType: "commercial",
    status: "available",
    address: { street: "1 Funland Dr", city: "Wisconsin Dells", state: "WI", zipcode: "53965", country: "USA" },
    location: { type: "Point", coordinates: [-89.783, 43.627] },
    amenities: ["Water Park", "Conference Center", "Restaurant", "Spa", "Pool"],
    isFeatured: true,
    meta: { furnished: true, yearBuilt: 2010 }
  },
  {
    title: "Tudor Revival Home",
    description: "Lovely Tudor Revival home with half-timbering and a steeply pitched roof. Leaded glass windows, a grand fireplace, and original hardwood floors. Updated kitchen and baths. Mature gardens.",
    price: 725000,
    bedrooms: 4,
    bathrooms: 2,
    area: 2800,
    propertyType: "house",
    status: "available",
    address: { street: "10 Tudor Ln", city: "Cincinnati", state: "OH", zipcode: "45201", country: "USA" },
    location: { type: "Point", coordinates: [-84.512, 39.103] },
    amenities: ["Leaded Glass", "Fireplace", "Hardwood Floors", "Garden"],
    isFeatured: false,
    meta: { furnished: false, yearBuilt: 1930 }
  },
  {
    title: "Flex Space with Office and Warehouse",
    description: "Versatile flex space combining office and warehouse. Front office area with 3 rooms, kitchen, and restroom. Rear warehouse with 16-foot clearance, roll-up door, and heavy power. Great for contractors.",
    price: 490000,
    bedrooms: 0,
    bathrooms: 2,
    area: 3500,
    propertyType: "commercial",
    status: "available",
    address: { street: "200 Flex Dr", city: "Salt Lake City", state: "UT", zipcode: "84102", country: "USA" },
    location: { type: "Point", coordinates: [-111.89, 40.76] },
    amenities: ["Office", "Warehouse", "Roll-Up Door", "Parking", "Security"],
    isFeatured: false,
    meta: { furnished: false, yearBuilt: 2013 }
  },
  {
    title: "Tropical Beach Bungalow",
    description: "Colorful beach bungalow with tropical landscaping. Open-air living with louvered windows, ceiling fans throughout, and an outdoor shower. Walking distance to the beach and local surf break.",
    price: 450000,
    bedrooms: 2,
    bathrooms: 1,
    area: 700,
    propertyType: "house",
    status: "available",
    address: { street: "1 Beach Bungalow Ln", city: "Kihei", state: "HI", zipcode: "96753", country: "USA" },
    location: { type: "Point", coordinates: [-156.455, 20.78] },
    amenities: ["Outdoor Shower", "Ceiling Fans", "Near Beach", "Tropical Garden"],
    isFeatured: false,
    meta: { furnished: true, yearBuilt: 1985 }
  },
  {
    title: "Co-Living Property with 10 Rooms",
    description: "Purpose-built co-living property with 10 private rooms, shared kitchen and living areas, laundry, and a courtyard. High occupancy with waiting list. Managed by a professional co-living operator.",
    price: 1600000,
    bedrooms: 10,
    bathrooms: 5,
    area: 5000,
    propertyType: "other",
    status: "rented",
    address: { street: "300 Co-Living Blvd", city: "Oakland", state: "CA", zipcode: "94601", country: "USA" },
    location: { type: "Point", coordinates: [-122.271, 37.804] },
    amenities: ["Common Kitchen", "Coworking", "Laundry", "Courtyard", "Bike Storage"],
    isFeatured: false,
    meta: { furnished: true, yearBuilt: 2019 }
  },
  {
    title: "Cape Cod Beach House",
    description: "Classic Cape Cod beach house with weathered shingles and white trim. Open plan living with a fireplace, eat-in kitchen, and a sunroom. Walk to the beach, shops, and seafood restaurants.",
    price: 850000,
    bedrooms: 3,
    bathrooms: 2,
    area: 1800,
    propertyType: "house",
    status: "available",
    address: { street: "1 Cape Cod Way", city: "Provincetown", state: "MA", zipcode: "02657", country: "USA" },
    location: { type: "Point", coordinates: [-70.186, 42.058] },
    amenities: ["Near Beach", "Sunroom", "Fireplace", "Outdoor Shower", "Deck"],
    isFeatured: false,
    meta: { furnished: false, yearBuilt: 1978 }
  },
  {
    title: "Apartment with Home Office",
    description: "Well-designed apartment with a dedicated home office space. Open living area, modern kitchen with island, and a balcony. Building features a coworking lounge and package concierge.",
    price: 420000,
    bedrooms: 2,
    bathrooms: 1,
    area: 900,
    propertyType: "apartment",
    status: "available",
    address: { street: "200 Work From Home Dr", city: "Austin", state: "TX", zipcode: "73303", country: "USA" },
    location: { type: "Point", coordinates: [-97.74, 30.28] },
    amenities: ["Home Office", "Coworking Lounge", "Balcony", "Gym", "Package Room"],
    isFeatured: false,
    meta: { furnished: false, yearBuilt: 2022 }
  },
  {
    title: "Industrial Property with Rail Access",
    description: "Heavy industrial property with direct rail access. 50,000 sq ft manufacturing building with 30-foot clear height, heavy crane, and multiple loading docks. Located in an enterprise zone with tax incentives.",
    price: 4200000,
    bedrooms: 0,
    bathrooms: 6,
    area: 50000,
    propertyType: "commercial",
    status: "available",
    address: { street: "1000 Industrial Pkwy", city: "Gary", state: "IN", zipcode: "46401", country: "USA" },
    location: { type: "Point", coordinates: [-87.337, 41.593] },
    amenities: ["Rail Access", "Crane", "Loading Docks", "Enterprise Zone", "Security"],
    isFeatured: false,
    meta: { furnished: false, yearBuilt: 2000 }
  },
  {
    title: "Glass House Architectural Icon",
    description: "Award-winning glass house by a renowned architect. Walls of glass blur the line between indoors and out. Minimalist design with floating stairs, a reflecting pool, and sculptural landscape.",
    price: 3800000,
    bedrooms: 3,
    bathrooms: 3,
    area: 3200,
    propertyType: "house",
    status: "available",
    address: { street: "1 Glass House Ln", city: "Los Angeles", state: "CA", zipcode: "90024", country: "USA" },
    location: { type: "Point", coordinates: [-118.435, 34.07] },
    amenities: ["Reflecting Pool", "Architectural", "Smart Home", "Infinity Pool", "City View"],
    isFeatured: true,
    meta: { furnished: true, yearBuilt: 2020 }
  },
  {
    title: "Bed and Breakfast Inn",
    description: "Charming 6-room bed and breakfast inn with high ratings. Common areas include a parlor, dining room, and wraparound porch. Separate owner's quarters. Established clientele and online presence.",
    price: 1250000,
    bedrooms: 6,
    bathrooms: 6,
    area: 4500,
    propertyType: "commercial",
    status: "available",
    address: { street: "1 Inn Keepers Way", city: "Newport", state: "RI", zipcode: "02840", country: "USA" },
    location: { type: "Point", coordinates: [-71.312, 41.49] },
    amenities: ["Commercial Kitchen", "Dining Room", "Porch", "Garden", "Parking"],
    isFeatured: true,
    meta: { furnished: true, yearBuilt: 1880 }
  },
  {
    title: "Shipping Container Home",
    description: "Innovative shipping container home with modern design. Three containers arranged around a courtyard. Energy-efficient with solar, green roof, and recycled materials. Compact but surprisingly spacious.",
    price: 320000,
    bedrooms: 2,
    bathrooms: 2,
    area: 960,
    propertyType: "house",
    status: "available",
    address: { street: "1 Container Ct", city: "Albuquerque", state: "NM", zipcode: "87101", country: "USA" },
    location: { type: "Point", coordinates: [-106.65, 35.084] },
    amenities: ["Solar", "Green Roof", "Courtyard", "Sustainable Design"],
    isFeatured: true,
    meta: { furnished: false, yearBuilt: 2021 }
  },
  {
    title: "Downtown Parking Garage",
    description: "Revenue-generating parking garage in the downtown core. 300 spaces with monthly and hourly parking. Included: car wash bay, EV charging stations, and a manager's office. Strong cash flow.",
    price: 4800000,
    bedrooms: 0,
    bathrooms: 2,
    area: 100000,
    propertyType: "commercial",
    status: "available",
    address: { street: "100 Parking Plaza", city: "Seattle", state: "WA", zipcode: "98103", country: "USA" },
    location: { type: "Point", coordinates: [-122.34, 47.62] },
    amenities: ["EV Charging", "Car Wash", "Security", "Elevator", "Monthly Parking"],
    isFeatured: false,
    meta: { furnished: false, yearBuilt: 2015 }
  },
  {
    title: "Artist Compound with Studios",
    description: "Unique artist compound featuring a main residence and 3 separate studio spaces. Galleries, kiln room, and matting/framing workshop. Set on 2 acres with gardens and a pond for inspiration.",
    price: 780000,
    bedrooms: 3,
    bathrooms: 3,
    area: 3000,
    propertyType: "other",
    status: "available",
    address: { street: "1 Artist Colony Rd", city: "Taos", state: "NM", zipcode: "87571", country: "USA" },
    location: { type: "Point", coordinates: [-105.573, 36.407] },
    amenities: ["Studios", "Kiln", "Gallery Space", "Garden", "Pond"],
    isFeatured: false,
    meta: { furnished: false, yearBuilt: 1998 }
  },
  {
    title: "Mountain Bunker Off-Grid Property",
    description: "Self-sufficient off-grid property with a reinforced bunker-style home. Solar, wind, battery backup, well water, and septic. 40 acres of privacy with mountain views. Perfect for preppers or privacy seekers.",
    price: 550000,
    bedrooms: 2,
    bathrooms: 1,
    area: 1200,
    propertyType: "house",
    status: "available",
    address: { street: "1 Off Grid Rd", city: "Missoula", state: "MT", zipcode: "59801", country: "USA" },
    location: { type: "Point", coordinates: [-113.996, 46.872] },
    amenities: ["Solar", "Wind Power", "Well Water", "Septic", "Privacy"],
    isFeatured: false,
    meta: { furnished: false, yearBuilt: 2017 }
  },
  {
    title: "Lighthouse Tower Residence",
    description: "One-of-a-kind historic lighthouse converted into a residence. Spiral staircase leads to a circular living area with 360-degree ocean views. Modern kitchen and bath. Truly unique coastal property.",
    price: 1500000,
    bedrooms: 2,
    bathrooms: 1,
    area: 1200,
    propertyType: "other",
    status: "available",
    address: { street: "1 Lighthouse Point", city: "Bar Harbor", state: "ME", zipcode: "04609", country: "USA" },
    location: { type: "Point", coordinates: [-68.204, 44.387] },
    amenities: ["Ocean View", "Historic", "Private Beach", "Deck"],
    isFeatured: true,
    meta: { furnished: false, yearBuilt: 1892 }
  },
  {
    title: "Sustainable Earthship Home",
    description: "Self-sustaining Earthship home built into the hillside. Passive solar heating, thermal mass walls, greenhouse, and water recycling system. Three bedrooms with beautiful natural light.",
    price: 380000,
    bedrooms: 3,
    bathrooms: 2,
    area: 1800,
    propertyType: "house",
    status: "available",
    address: { street: "1 Earthship Way", city: "Taos", state: "NM", zipcode: "87571", country: "USA" },
    location: { type: "Point", coordinates: [-105.57, 36.4] },
    amenities: ["Passive Solar", "Greenhouse", "Water Recycling", "Thermal Mass"],
    isFeatured: false,
    meta: { furnished: false, yearBuilt: 2014 }
  }
];

async function seedProperties() {
  try {
    console.log("Connecting to MongoDB...");
    await mongoose.connect(`${process.env.MONGODB_URI}/${DB_NAME}`);
    console.log("Connected to MongoDB");

    let user = await User.findOne();
    if (!user) {
      user = await User.create({
        username: "seed_admin",
        email: "seed@example.com",
        password: "password123",
      });
      console.log("Created seed user:", user._id);
    }
    console.log("Using user:", user._id);

    await Property.deleteMany({});
    console.log("Cleared existing properties");

    const result = await Property.insertMany(
      properties.map((p) => ({ ...p, postedBy: user._id, approved: true }))
    );
    console.log(`Inserted ${result.length} properties`);

    await mongoose.disconnect();
    console.log("Done");
  } catch (error) {
    console.error("Seed error:", error);
    process.exit(1);
  }
}

seedProperties();
